[package]
name = "turborepo-storage-adapter"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = { workspace = true }
anyhow = { workspace = true }
bytes = { workspace = true }
futures = { workspace = true }
hyper = { workspace = true }
thiserror = { workspace = true }
